server:
  port: ${SERVER_PORT:8081}
spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5442/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
